config/routes.rb
Rails.application.routes.draw do
  resources :tools
end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  def index
    @tools = Tool.all
  end

  def show
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.create(tool_params)
    redirect_to tools_path #index
  end

  def edit
  end

  def update
    @tool.update(tool_params)
    redirect_to @tool
  end

  def destroy
    @tool.destroy
    redirect_to tools_path
  end

private

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :use)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :use %>
  <%= f.text_field :use %>
  <br>

  <%= f.submit %>
<% end %>

app/views/tools/edit.html.erb
<h1>Edit Tool</h1>

<%= render partial: "form" %>

app/views/tools/index.html.erb
<h1>All Tools</h1>

<% @tools.each do |tool| %>
  <p><%= link_to(tool.name, tool) %> (<%= tool.use %>)</p>
  <%= link_to "edit", edit_tool_path(tool) %>
  <%= link_to "delete", tool_path(tool), method: :delete %>
<% end %>

<%= link_to "New tool", new_tool_path %>

app/views/tools/new.html.erb
<h1>New Tool</h1>

<%= render partial: "form" %>

app/views/tools/show.html.erb
<h1><%= @tool.name %></h1>
<p><%= @tool.use %></p>